drivetest
SciBorgs/Crescendo-2024 pull request #21
Opened 2024-02-14 04:21 UTC by moxior

Added goTo command

2024-02-15 22:26 UTC, sigalrmp requested changes

2024-02-15 22:26 UTC, sigalrmp commented on src/main/java/org/sciborgs1155/robot/drive/Drive.java
> +    double output = pid.calculate(magnitude);
basically everything here should go inside the run command

2024-02-15 22:26 UTC, sigalrmp commented on src/main/java/org/sciborgs1155/robot/drive/Drive.java
> +    var pid =
this can be outside of the method and make sure to set the goal (and make sure it makes sense)

2024-03-29 22:51 UTC, AngleSideAngle commented
- [ ]

2024-03-29 22:51 UTC, closed without merging