Intake
SciBorgs/Crescendo-2024 pull request #5
Opened 2024-01-22 21:20 UTC by dannynotsmart

Merge intake into main.

2024-01-24 16:09 UTC, sigalrmp requested changes

2024-01-24 16:09 UTC, sigalrmp commented on src/main/java/org/sciborgs1155/robot/intake/Intake.java
> +  public Command spin(boolean forward) {
could you make this two separate commands? (an intake and an outtake)

2024-01-24 16:09 UTC, sigalrmp commented on src/main/java/org/sciborgs1155/robot/intake/Intake.java
> +public class Intake extends SubsystemBase implements Logged, AutoCloseable {
can you make an Intake subsystem in Robot?

2024-01-28 03:14 UTC, AngleSideAngle approved these changes

2024-02-01 21:27 UTC, closed without merging