Led rewrite
SciBorgs/Crescendo-2024 pull request #72
Opened 2024-05-20 19:56 UTC by HenryLi-0

changes:
- no led enum, replaced with commands
- same classic led colors, the ones you know and love!

2024-05-21 23:22 UTC, kishan243 commented on src/main/java/org/sciborgs1155/robot/Robot.java
> +    led.setDefaultCommand(led.alliance());
The default command should be a color when there is no note in the robot . You can do this for when the robot is disabled instead.

2024-05-23 00:52 UTC, Yxhej requested changes

2024-05-23 00:52 UTC, Yxhej commented on src/main/java/org/sciborgs1155/robot/led/LedStrip.java
> +          if (Math.round(Math.random()) == 0) {
This line of code can be easily simplified by testing if `Math.random() < 0.5. `

2024-05-23 00:52 UTC, Yxhej commented on src/main/java/org/sciborgs1155/robot/led/LedStrip.java
> +  public static AddressableLEDBuffer genBuffer(Function<Integer, Color> f) {
Documentation check 🔥🔥🔥

2024-05-24 18:52 UTC, Yxhej commented on src/main/java/org/sciborgs1155/robot/led/LedStrip.java
> +  public static AddressableLEDBuffer genBuffer(Function<Integer, Color> f) {
Cool change (honestly did not know that was a thing), but I meant to add a javadoc explaining what exactly it takes in and what it does. To unfamiliar eyes, the usage of this (and buffers in general) is unclear. Be as concise as possible.

2024-05-25 14:01 UTC, Yxhej approved these changes

2024-05-25 15:47 UTC, merged