Vision
SciBorgs/Crescendo-2024 pull request #8
Opened 2024-01-24 21:32 UTC by moxior

Added rear and front cameras along with respective pose estimators to the previous template.

2024-01-29 23:12 UTC, AngleSideAngle requested changes

2024-01-29 23:12 UTC, anglesideangle commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  private final PhotonCamera frontCamera;
there should be lists for `PhotonCamera`, `PhotonPoseEstimator`, and `PhotonCameraSim`

2024-01-29 23:12 UTC, anglesideangle commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  public Vision() {
vision would take in a list of `CameraConfig` records with all data needed to describe a camera
eg.
```java
public static record CameraConfig(String name, Transform3d transformation) {}
```
```java
public Vision(CameraConfig... cameras) {
...
}
```

2024-01-29 23:12 UTC, anglesideangle commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +    return Stream.of(frontPhotonEstimator, rearPhotonEstimator)
here you'd do estimators.stream()

2024-01-29 23:12 UTC, anglesideangle commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  private double lastEstTimestamp = 0;
this doesn't seem very useful, you can get rid of any mention of it

2024-01-29 23:12 UTC, AngleSideAngle commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  public Optional<EstimatedRobotPose> getEstimatedGlobalPose(
you can get rid of this method, since `getEstimatedGlobalPoses` is the same thing, but works for multiple cameras

2024-01-29 23:12 UTC, AngleSideAngle commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  public void simulationPeriodic(Pose2d robotSimPose) {
use `addPeriodic` in `Robot.java` to run this periodically when the robot is being simulated

2024-01-29 23:12 UTC, AngleSideAngle commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  public Field2d getSimDebugField() {
this also isn't necessary

2024-01-29 23:12 UTC, AngleSideAngle commented on src/main/java/org/sciborgs1155/robot/vision/VisionConstants.java
> +  public static final String FRONT_CAMERA_NAME = "placeholder";
again, we need a `CameraConfig` record, with two instances, one for either camera, here

2024-02-01 18:01 UTC, AngleSideAngle requested changes

2024-02-01 18:01 UTC, anglesideangle commented on src/main/java/org/sciborgs1155/robot/Robot.java
> +  private final Vision vision = new Vision(null);
passing in null causes the builds to fail from a null ptr exception

2024-02-01 18:01 UTC, anglesideangle commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  private List<PhotonCameraSim> cameraSimList = new ArrayList<PhotonCameraSim>();
you should name these `cameras`, `estimators` and `simCameras`
the phrase "list" is redundant

2024-02-01 18:01 UTC, anglesideangle commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +      this.visionSim.addAprilTags(null);
pass in the apriltags, not null

2024-02-01 18:01 UTC, anglesideangle commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +    /*
delete this commented out code

2024-02-01 18:01 UTC, anglesideangle commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  /** A Field2d for visualizing our robot and objects on the field. */
```suggestion
```

2024-02-01 18:01 UTC, AngleSideAngle commented on src/main/java/org/sciborgs1155/robot/vision/VisionConstants.java
> +  public static final AprilTagFieldLayout kTagLayout =
this is the same variable as `TAG_LAYOUT`, it should be the thing you pass into the sim vision system as well

2024-02-01 18:01 UTC, AngleSideAngle commented on src/main/java/org/sciborgs1155/robot/vision/VisionConstants.java
> +  public static final CameraConfig FRONT_CAMERA_CONFIG =
good, pass these into the `vision` constructor in `Robot`

2024-02-10 04:32 UTC, sigalrmp approved these changes

2024-02-10 04:32 UTC, sigalrmp commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  private final PhotonCamera frontCamera;
everything, except for the sim stuff, can be initialized when they're declared, instead of in the constructor

2024-02-10 04:32 UTC, sigalrmp commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  public Matrix<N3, N1> getEstimationStdDevs(
This looks like it should be static

2024-02-10 04:32 UTC, sigalrmp commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  public Matrix<N3, N1> getEstimationStdDevs(
Also, where are you expecting this to be called from? The cameras are private and estimators, so it kind of has to be used inside of vision (which is not currently the case)

2024-02-10 04:32 UTC, sigalrmp commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  public void simulationPeriodic(Pose2d robotSimPose) {
Only subsystems have periodics that are actually called periodically (without us doing that manually). Currently, this is not a subsystem, but I'm pretty sure it should be

2024-02-10 04:32 UTC, sigalrmp commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +  public Optional<EstimatedRobotPose> getEstimatedGlobalPose(
with this one (and the next one) I don't really see the point in making them public, since you need to pass them a camera and a poseEstimator, and our cameras and pose estimators are private fields of this class. 

This probably means there should be some separate methods that can reasonably be called from outside of Vision, so we can get some functionality out of all of this

2024-02-10 04:32 UTC, sigalrmp commented on src/main/java/org/sciborgs1155/robot/vision/Vision.java
> +public class Vision {
I think it'd be helpful for you to think for a second about what functionality this should ultimately have (i.e. if we had an io class for vision, what methods would it contain?). Right now, it doesn't seem like it's quite at the point yet where we can use it from other parts of the code

2024-02-10 04:35 UTC, merged